/* Generated By:JavaCC: Do not edit this line. CommandLineParserConstants.java */
package givenClauseLoop.CommandLineParser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface CommandLineParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int FIFO_STRATEGY = 4;
  /** RegularExpression Id. */
  int BFS_STRATEGY = 5;
  /** RegularExpression Id. */
  int LOOP_TYPE = 6;
  /** RegularExpression Id. */
  int TIME = 7;
  /** RegularExpression Id. */
  int RESEARCH_STRATEGY = 8;
  /** RegularExpression Id. */
  int FILEPATH = 9;
  /** RegularExpression Id. */
  int NUMERIC = 10;
  /** RegularExpression Id. */
  int CHAR1 = 11;
  /** RegularExpression Id. */
  int CHAR2 = 12;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\n\"",
    "\"\\r\"",
    "\"-fifo\"",
    "<BFS_STRATEGY>",
    "<LOOP_TYPE>",
    "<TIME>",
    "<RESEARCH_STRATEGY>",
    "<FILEPATH>",
    "<NUMERIC>",
    "<CHAR1>",
    "<CHAR2>",
    "\"\\t\"",
    "\"-man\"",
  };

}
