/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */
package givenClauseLoop.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT = 5;
  /** RegularExpression Id. */
  int VLINE = 6;
  /** RegularExpression Id. */
  int NOT = 7;
  /** RegularExpression Id. */
  int OPEN_BRACKET = 8;
  /** RegularExpression Id. */
  int CLOSE_BRACKET = 9;
  /** RegularExpression Id. */
  int DOT = 10;
  /** RegularExpression Id. */
  int COMMA = 11;
  /** RegularExpression Id. */
  int CNF = 12;
  /** RegularExpression Id. */
  int LOWER_WORD = 13;
  /** RegularExpression Id. */
  int UPPER_WORD = 14;
  /** RegularExpression Id. */
  int SINGLE_QUOTED = 15;
  /** RegularExpression Id. */
  int LOWER_ALFA = 16;
  /** RegularExpression Id. */
  int UPPER_ALFA = 17;
  /** RegularExpression Id. */
  int DOLLAR_LOWER_ALFA = 18;
  /** RegularExpression Id. */
  int DOLLAR_UPPER_ALFA = 19;
  /** RegularExpression Id. */
  int ALFA_NUMERIC = 20;
  /** RegularExpression Id. */
  int DEF_SYS = 21;
  /** RegularExpression Id. */
  int UNDERSCORE = 22;
  /** RegularExpression Id. */
  int SINGLE_QUOTE = 23;
  /** RegularExpression Id. */
  int SQ_CHAR = 24;
  /** RegularExpression Id. */
  int INTEGER = 25;
  /** RegularExpression Id. */
  int SIGNED_INTEGER = 26;
  /** RegularExpression Id. */
  int DECIMAL = 27;
  /** RegularExpression Id. */
  int SIGN = 28;
  /** RegularExpression Id. */
  int NUMERIC = 29;
  /** RegularExpression Id. */
  int ZERO_NUMERIC = 30;
  /** RegularExpression Id. */
  int NON_ZERO_NUMERIC = 31;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<SINGLE_LINE_COMMENT>",
    "\"|\"",
    "\"~\"",
    "\"(\"",
    "\")\"",
    "\".\"",
    "\",\"",
    "\"cnf\"",
    "<LOWER_WORD>",
    "<UPPER_WORD>",
    "<SINGLE_QUOTED>",
    "<LOWER_ALFA>",
    "<UPPER_ALFA>",
    "<DOLLAR_LOWER_ALFA>",
    "<DOLLAR_UPPER_ALFA>",
    "<ALFA_NUMERIC>",
    "<DEF_SYS>",
    "\"_\"",
    "\"\\\'\"",
    "<SQ_CHAR>",
    "<INTEGER>",
    "<SIGNED_INTEGER>",
    "<DECIMAL>",
    "<SIGN>",
    "<NUMERIC>",
    "<ZERO_NUMERIC>",
    "<NON_ZERO_NUMERIC>",
  };

}
