/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */
package givenClauseLoop;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int EqNotEq = 6;
  /** RegularExpression Id. */
  int CADR = 9;
  /** RegularExpression Id. */
  int PRED = 10;
  /** RegularExpression Id. */
  int FUNVAR = 11;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT = 16;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"-\"",
    "\"(\"",
    "\")\"",
    "\";\"",
    "\",\"",
    "<EqNotEq>",
    "\"atom\"",
    "\"cons\"",
    "<CADR>",
    "<PRED>",
    "<FUNVAR>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<SINGLE_LINE_COMMENT>",
    "\"cnf\"",
    "\".\"",
  };

}
