/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */
package givenClauseLoop;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT = 5;
  /** RegularExpression Id. */
  int SIGN = 6;
  /** RegularExpression Id. */
  int SINGLE_QUOTE = 7;
  /** RegularExpression Id. */
  int VLINE = 8;
  /** RegularExpression Id. */
  int NOT = 9;
  /** RegularExpression Id. */
  int OPEN_BRACKET = 10;
  /** RegularExpression Id. */
  int CLOSE_BRACKET = 11;
  /** RegularExpression Id. */
  int DOT = 12;
  /** RegularExpression Id. */
  int COMMA = 13;
  /** RegularExpression Id. */
  int UNDERSCORE = 14;
  /** RegularExpression Id. */
  int DEF_SYS = 15;
  /** RegularExpression Id. */
  int CNF = 16;
  /** RegularExpression Id. */
  int NUMERIC = 17;
  /** RegularExpression Id. */
  int ZERO_NUMERIC = 18;
  /** RegularExpression Id. */
  int NON_ZERO_NUMERIC = 19;
  /** RegularExpression Id. */
  int LOWER_ALFA = 20;
  /** RegularExpression Id. */
  int UPPER_ALFA = 21;
  /** RegularExpression Id. */
  int DOLLAR_LOWER_ALFA = 22;
  /** RegularExpression Id. */
  int DOLLAR_UPPER_ALFA = 23;
  /** RegularExpression Id. */
  int ALFA_NUMERIC = 24;
  /** RegularExpression Id. */
  int SQ_CHAR = 25;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<SINGLE_LINE_COMMENT>",
    "<SIGN>",
    "\"\\\'\"",
    "\"|\"",
    "\"~\"",
    "\"(\"",
    "\")\"",
    "\".\"",
    "\",\"",
    "\"_\"",
    "<DEF_SYS>",
    "\"cnf\"",
    "<NUMERIC>",
    "<ZERO_NUMERIC>",
    "<NON_ZERO_NUMERIC>",
    "<LOWER_ALFA>",
    "<UPPER_ALFA>",
    "<DOLLAR_LOWER_ALFA>",
    "<DOLLAR_UPPER_ALFA>",
    "<ALFA_NUMERIC>",
    "<SQ_CHAR>",
  };

}
