/* Generated By:JavaCC: Do not edit this line. Parser.java */
package givenClauseLoop;

//import java.util.*;
public class Parser implements ParserConstants {
        /**	* Conjunctive Normal Form (CNF) Formulae's Parser.	* Based on CNF fragment of TPTP syntax	* http://www.tptp.org	* http://www.cs.miami.edu/~tptp/TPTP/SyntaxBNF.html	*	*@param input CNF formulae	*@param output	*/
        public static void parsing(String input,Object output) throws Exception{
                output="ciao";
                try{
                        new Parser(new java.io.StringReader(input)).TPTP_file();
                }catch(Throwable e){
                        // Catching Throwable is ugly but JavaCC throws Error objects!                        throw new ParseException("Syntax check failed: " + e.getMessage());
                }
    }

/*** All the contents of the file*/
  static final public void TPTP_file() throws ParseException {
    TPTP_input();
    jj_consume_token(0);
  }

/**  * Set of CNF annotated formulae */
  static final public void TPTP_input() throws ParseException {
    label_1:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case CNF:
        ;
        break;
      default:
        jj_la1[0] = jj_gen;
        break label_1;
      }
      cnf_annotated();
    }
  }

/** * An annotated CNF formula */
  static final public void cnf_annotated() throws ParseException {
    jj_consume_token(CNF);
    jj_consume_token(OPEN_BRACKET);
    name();
    jj_consume_token(COMMA);
    formula_role();
    jj_consume_token(COMMA);
    cnf_formula();
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case COMMA:
      jj_consume_token(COMMA);
      annotations();
      break;
    default:
      jj_la1[1] = jj_gen;
      ;
    }
    jj_consume_token(CLOSE_BRACKET);
    jj_consume_token(DOT);
  }

/*** The CNF name*/
  static final public void name() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case SINGLE_QUOTE:
    case LOWER_ALFA:
    case DOLLAR_LOWER_ALFA:
      atomic_word();
      break;
    case SIGN:
    case ZERO_NUMERIC:
    case NON_ZERO_NUMERIC:
      integer();
      break;
    default:
      jj_la1[2] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

/*** The CNF formula role*/
  static final public void formula_role() throws ParseException {
    lower_word();
  }

/*** The CNF annotations*/
  static final public void annotations() throws ParseException {
    label_2:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case SINGLE_QUOTE:
      case LOWER_ALFA:
      case DOLLAR_LOWER_ALFA:
        atomic_word();
        break;
      case UPPER_ALFA:
      case DOLLAR_UPPER_ALFA:
        upper_word();
        break;
      default:
        jj_la1[3] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case SINGLE_QUOTE:
      case LOWER_ALFA:
      case UPPER_ALFA:
      case DOLLAR_LOWER_ALFA:
      case DOLLAR_UPPER_ALFA:
        ;
        break;
      default:
        jj_la1[4] = jj_gen;
        break label_2;
      }
    }
  }

/******************************************************************  CNF FORMULAE (variables implicitly universally quantified) ******************************************************************/
  static final public void cnf_formula() throws ParseException {
    jj_consume_token(OPEN_BRACKET);
    literal();
    label_3:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case VLINE:
        ;
        break;
      default:
        jj_la1[5] = jj_gen;
        break label_3;
      }
      jj_consume_token(VLINE);
      literal();
    }
    jj_consume_token(CLOSE_BRACKET);
  }

// void disjunction():{}{	disjunction() <VLINE> literal() | literal()	}   static final public void literal() throws ParseException {
          Token t=null;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case NOT:
      t = jj_consume_token(NOT);
      break;
    default:
      jj_la1[6] = jj_gen;
      ;
    }
    atomic_formula();

  }

  static final public void atomic_formula() throws ParseException {
    atomic_word();
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case OPEN_BRACKET:
      jj_consume_token(OPEN_BRACKET);
      arguments();
      jj_consume_token(CLOSE_BRACKET);
      break;
    default:
      jj_la1[7] = jj_gen;
      ;
    }
  }

/******************************************************************		TERM	***************************************************************************/
  static final public void arguments() throws ParseException {
    term();
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case COMMA:
      jj_consume_token(COMMA);
      term();
      break;
    default:
      jj_la1[8] = jj_gen;
      ;
    }
  }

  static final public void term() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case SINGLE_QUOTE:
    case LOWER_ALFA:
    case DOLLAR_LOWER_ALFA:
      function_term();
      break;
    case UPPER_ALFA:
    case DOLLAR_UPPER_ALFA:
      upper_word();
      break;
    default:
      jj_la1[9] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  static final public void function_term() throws ParseException {
    atomic_word();
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case OPEN_BRACKET:
      jj_consume_token(OPEN_BRACKET);
      arguments();
      jj_consume_token(CLOSE_BRACKET);
      break;
    default:
      jj_la1[10] = jj_gen;
      ;
    }
  }

/******************************************************************		WORD	***************************************************************************/
  static final public String atomic_word() throws ParseException {
          String s;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case LOWER_ALFA:
    case DOLLAR_LOWER_ALFA:
      s = lower_word();
      break;
    case SINGLE_QUOTE:
      s = single_quoted();
          {if (true) return s;}
      break;
    default:
      jj_la1[11] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  static final public String upper_word() throws ParseException {
                Token   t1=null,
                                t2=null;
                StringBuffer s1 = new StringBuffer();
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case DOLLAR_UPPER_ALFA:
      t1 = jj_consume_token(DOLLAR_UPPER_ALFA);
      break;
    case UPPER_ALFA:
      t1 = jj_consume_token(UPPER_ALFA);
      break;
    default:
      jj_la1[12] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    label_4:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case ALFA_NUMERIC:
        ;
        break;
      default:
        jj_la1[13] = jj_gen;
        break label_4;
      }
      t2 = jj_consume_token(ALFA_NUMERIC);
                                                                           s1.append(t2.image.charAt(0));
    }
          {if (true) return  t1.image + s1.toString();}
    throw new Error("Missing return statement in function");
  }

  static final public String lower_word() throws ParseException {
                Token   t1=null,
                                t2=null;
                StringBuffer s1 = new StringBuffer();
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case DOLLAR_LOWER_ALFA:
      t1 = jj_consume_token(DOLLAR_LOWER_ALFA);
      break;
    case LOWER_ALFA:
      t1 = jj_consume_token(LOWER_ALFA);
      break;
    default:
      jj_la1[14] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    label_5:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case ALFA_NUMERIC:
        ;
        break;
      default:
        jj_la1[15] = jj_gen;
        break label_5;
      }
      t2 = jj_consume_token(ALFA_NUMERIC);
                                                                           s1.append(t2.image.charAt(0));
    }
          {if (true) return  t1.image + s1.toString();}
    throw new Error("Missing return statement in function");
  }

/*** A a word in quoted* It can contain also special character apart from ' and \*/
  static final public String single_quoted() throws ParseException {
                Token   t1=null,
                                t2=null;
                StringBuffer s=new StringBuffer();
    t1 = jj_consume_token(SINGLE_QUOTE);
    label_6:
    while (true) {
      t2 = jj_consume_token(SQ_CHAR);
                                          s.append(t2.image.charAt(0));
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case SQ_CHAR:
        ;
        break;
      default:
        jj_la1[16] = jj_gen;
        break label_6;
      }
    }
    jj_consume_token(SINGLE_QUOTE);
          {if (true) return t1.image + s.toString() + t1.image;}
    throw new Error("Missing return statement in function");
  }

/******************************************************************		NUMBER	***************************************************************************/
  static final public String integer() throws ParseException {
                String s;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case SIGN:
      s = signed_integer();
      break;
    case ZERO_NUMERIC:
    case NON_ZERO_NUMERIC:
      s = decimal();
          {if (true) return s;}
      break;
    default:
      jj_la1[17] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  static final public String signed_integer() throws ParseException {
                Token t=null;
                String s;
    t = jj_consume_token(SIGN);
    s = decimal();
          {if (true) return t.image + s;}
    throw new Error("Missing return statement in function");
  }

  static final public String decimal() throws ParseException {
                Token t=null;
                String s;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case ZERO_NUMERIC:
      t = jj_consume_token(ZERO_NUMERIC);
      break;
    case NON_ZERO_NUMERIC:
      s = positive_decimal();
        {if (true) return (t!=null)? t.image : s;}
      break;
    default:
      jj_la1[18] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  static final public String positive_decimal() throws ParseException {
                Token   t1=null,
                                t2=null;
                StringBuffer s=new StringBuffer();
    t1 = jj_consume_token(NON_ZERO_NUMERIC);
    label_7:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case NUMERIC:
        ;
        break;
      default:
        jj_la1[19] = jj_gen;
        break label_7;
      }
      t2 = jj_consume_token(NUMERIC);
                                              s.append(t2.image.charAt(0));
    }
          {if (true) return t1.image + s;}
    throw new Error("Missing return statement in function");
  }

  static private boolean jj_initialized_once = false;
  /** Generated Token Manager. */
  static public ParserTokenManager token_source;
  static SimpleCharStream jj_input_stream;
  /** Current token. */
  static public Token token;
  /** Next token. */
  static public Token jj_nt;
  static private int jj_ntk;
  static private int jj_gen;
  static final private int[] jj_la1 = new int[20];
  static private int[] jj_la1_0;
  static {
      jj_la1_init_0();
   }
   private static void jj_la1_init_0() {
      jj_la1_0 = new int[] {0x10000,0x2000,0x5c00c0,0xf00080,0xf00080,0x100,0x200,0x400,0x2000,0xf00080,0x400,0x500080,0xa00000,0x1000000,0x500000,0x1000000,0x2000000,0xc0040,0xc0000,0x20000,};
   }

  /** Constructor with InputStream. */
  public Parser(java.io.InputStream stream) {
     this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public Parser(java.io.InputStream stream, String encoding) {
    if (jj_initialized_once) {
      System.out.println("ERROR: Second call to constructor of static parser.  ");
      System.out.println("       You must either use ReInit() or set the JavaCC option STATIC to false");
      System.out.println("       during parser generation.");
      throw new Error();
    }
    jj_initialized_once = true;
    try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source = new ParserTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 20; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  static public void ReInit(java.io.InputStream stream) {
     ReInit(stream, null);
  }
  /** Reinitialise. */
  static public void ReInit(java.io.InputStream stream, String encoding) {
    try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 20; i++) jj_la1[i] = -1;
  }

  /** Constructor. */
  public Parser(java.io.Reader stream) {
    if (jj_initialized_once) {
      System.out.println("ERROR: Second call to constructor of static parser. ");
      System.out.println("       You must either use ReInit() or set the JavaCC option STATIC to false");
      System.out.println("       during parser generation.");
      throw new Error();
    }
    jj_initialized_once = true;
    jj_input_stream = new SimpleCharStream(stream, 1, 1);
    token_source = new ParserTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 20; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  static public void ReInit(java.io.Reader stream) {
    jj_input_stream.ReInit(stream, 1, 1);
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 20; i++) jj_la1[i] = -1;
  }

  /** Constructor with generated Token Manager. */
  public Parser(ParserTokenManager tm) {
    if (jj_initialized_once) {
      System.out.println("ERROR: Second call to constructor of static parser. ");
      System.out.println("       You must either use ReInit() or set the JavaCC option STATIC to false");
      System.out.println("       during parser generation.");
      throw new Error();
    }
    jj_initialized_once = true;
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 20; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(ParserTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 20; i++) jj_la1[i] = -1;
  }

  static private Token jj_consume_token(int kind) throws ParseException {
    Token oldToken;
    if ((oldToken = token).next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    if (token.kind == kind) {
      jj_gen++;
      return token;
    }
    token = oldToken;
    jj_kind = kind;
    throw generateParseException();
  }


/** Get the next Token. */
  static final public Token getNextToken() {
    if (token.next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    jj_gen++;
    return token;
  }

/** Get the specific Token. */
  static final public Token getToken(int index) {
    Token t = token;
    for (int i = 0; i < index; i++) {
      if (t.next != null) t = t.next;
      else t = t.next = token_source.getNextToken();
    }
    return t;
  }

  static private int jj_ntk() {
    if ((jj_nt=token.next) == null)
      return (jj_ntk = (token.next=token_source.getNextToken()).kind);
    else
      return (jj_ntk = jj_nt.kind);
  }

  static private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  static private int[] jj_expentry;
  static private int jj_kind = -1;

  /** Generate ParseException. */
  static public ParseException generateParseException() {
    jj_expentries.clear();
    boolean[] la1tokens = new boolean[26];
    if (jj_kind >= 0) {
      la1tokens[jj_kind] = true;
      jj_kind = -1;
    }
    for (int i = 0; i < 20; i++) {
      if (jj_la1[i] == jj_gen) {
        for (int j = 0; j < 32; j++) {
          if ((jj_la1_0[i] & (1<<j)) != 0) {
            la1tokens[j] = true;
          }
        }
      }
    }
    for (int i = 0; i < 26; i++) {
      if (la1tokens[i]) {
        jj_expentry = new int[1];
        jj_expentry[0] = i;
        jj_expentries.add(jj_expentry);
      }
    }
    int[][] exptokseq = new int[jj_expentries.size()][];
    for (int i = 0; i < jj_expentries.size(); i++) {
      exptokseq[i] = jj_expentries.get(i);
    }
    return new ParseException(token, exptokseq, tokenImage);
  }

  /** Enable tracing. */
  static final public void enable_tracing() {
  }

  /** Disable tracing. */
  static final public void disable_tracing() {
  }

}
